[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if effects[ii].h_mult then'''
position = "before"
payload = '''
if effects[ii].h_chips then
	mod_percent = true
	hand_chips = mod_chips(hand_chips + effects[ii].h_chips)
	update_hand_text({delay = 0}, {chips = hand_chips})
	card_eval_status_text(G.hand.cards[i], 'chips', effects[ii].h_chips, percent)
end
'''
match_indent = false

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')'''
position = "after"
payload = '''
if G.GAME.twewy_top_gear then
	if card.ability.set == 'Joker' and card.config.center.rarity == 1 then
		card:set_edition({polychrome = true})
	end
end
'''
match_indent = false
